CREATE DATABASE INVENORY;

USE INVENORY;

CREATE TABLE SALESMAN (
SALESMAN_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR (30),
CITY VARCHAR(15),
COMMISSION DECIMAL(5.2)
);



CREATE TABLE CUSTOMER (
CUSTOMER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
CUSTOMER_NAME VARCHAR(30),
CITY VARCHAR(20),
GRADE NUMERIC (3),
SALESMAN_ID NUMERIC(5) references SALESMAN (SALESMAN_ID)
);


CREATE TABLE ORDERS(
ORD_NO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
PURCHASE_AMOUNT DECIMAL (8,2),
ORDER_DATE DATETIME default NOW(),
CUSTOMER_ID NUMERIC(5) references CUSTOMER (CUSTOMER_ID),
SALESMAN_ID NUMERIC (5) references SALESMAN (SALESMAN_ID)
);

DESC SALESMAN;

DROP TABLE ORDERS;

SHOW TABLES;

DESC ORDERS;
DROP TABLE ORDERS;

INSERT INTO SALESMAN (NAME,CITY,COMMISSION)
VALUES ("NAMAN","DARBHANGA",41.2);

SELECT * FROM SALESMAN;

DROP TABLE CUSTOMER;

INSERT INTO CUSTOMER (CUSTOMER_NAME,CITY,GRADE,SALESMAN_ID)
VALUES ("ABHINAV","DARBHANGA",5,1);

INSERT INTO ORDERS (PURCHASE_AMOUNT,CUSTOMER_ID,SALESMAN_ID) 
VALUES (699,1,1);

SELECT * FROM ORDERS;
